name: Deploy to Hostinger

on:
  push:
    tags:
      - "v*" # Escuta apenas eventos de tags que começam com "v"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Faça o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Obtenha a tag atual
      - name: Get current tag
        id: current_tag
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "current_tag=$tag" >> $GITHUB_ENV

      # 3. Exiba a tag para verificação
      - name: Display tag
        run: |
          echo "Deploying version $current_tag"

      # 4. Instale Node.js e Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 5. Instale dependências usando Yarn
      - name: Install dependencies
        run: yarn install

      # 6. Gere o build do projeto
      - name: Build project
        run: yarn build

      # 7. Deploy para a Hostinger via FTP
      - name: Deploy to Hostinger
        env:
          HOSTINGER_FTP_SERVER: ${{ secrets.FTP_SERVER }}
          HOSTINGER_FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          HOSTINGER_FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u $HOSTINGER_FTP_USERNAME,$HOSTINGER_FTP_PASSWORD $HOSTINGER_FTP_SERVER -e "
          set ssl:verify-certificate no;
          mirror -R ./dist/ /public_html/
          bye
          "
